name: Docker Buildx & Publish Image

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./scraper/dev/docker/Dockerfile.base
          platforms: linux/amd64 # chrome does not support arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-base:${{ github.run_number }},ghcr.io/${{ github.repository }}-base:latest

      - name: Build and push final image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./scraper/dev/docker/Dockerfile
          platforms: linux/amd64 # chrome does not support arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.run_number }},ghcr.io/${{ github.repository }}:latest